### ISSUE TITLE
[BUG] JS migrate script does not work (using Docker)

### ISSUE THREAD

**Issue by zseta** [scylladb/care-pet#118]
Hi there,

I've been following the instructions [outlined here.](https://github.com/scylladb/care-pet/tree/master/javascript) to build this project using JavaScript.

I get stuck when trying to run the [migrate script.](https://iot.scylladb.com/stable/build-with-javascript.html#migrate) (I'm using Docker)
```bash
npm run migrate -- --hosts 172.24.0.4
```

Error:
```bash
info: Bootstrapping database...
(node:96046) UnhandledPromiseRejectionWarning: ArgumentError: 'localDataCenter' is not defined in Client options and also was not specified in constructor. At least one is required. Available DCs are: [datacenter1]
    at setLocalDc (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/policies/load-balancing.js:860:11)
    at DefaultLoadBalancingPolicy.init (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/policies/load-balancing.js:565:7)
    at /home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/execution-profile.js:171:55
    at /home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/promise-utils.js:52:5
    at new Promise (<anonymous>)
    at Object.fromCallback (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/promise-utils.js:51:10)
    at ProfileManager.init (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/execution-profile.js:171:26)
    at Client._connect (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/node_modules/cassandra-driver/lib/client.js:515:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getClient (/home/attila/Documents/stuff/FY23Q1/scylla/care-pet/javascript/src/db.js:16:5)
(node:96046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:96046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Relevant part (likely):
`UnhandledPromiseRejectionWarning: ArgumentError: 'localDataCenter' is not defined in Client options and also was not specified in constructor. At least one is required. Available DCs are: [datacenter1]`

Any tips how to fix this? Let me know if you need more info from me!

Thank you!

PS: not related to the bug, but I could imagine this step being part of the setup process so users don't need to run it manually (at least for those who use Docker and not Cloud)

**Comment by zseta** [comment]
Looks like adding the `--datacenter` parameter solves this issue:
```
npm run migrate -- --hosts 172.24.0.4 --datacenter datacenter1
info: Bootstrapping database...
info: Creating keyspace...
info: Keyspace created
info: Migrating database...
info: Database migrated
```
Works for me

**Comment by zseta** [comment]
Later on in the tutorial, `--datacenter` is also needed when running the "pet collar simulation ":
```bash
npm run sensor -- --hosts 172.24.0.4 --measure 5s --buffer-interval 1m --datacenter datacenter1
```

**Comment by DanielHe4rt** [comment]
Fixed and merged!
