### ISSUE TITLE
Make preview command for docs doesn't work on MacOS

### ISSUE THREAD

**Issue by raoufchebri** [scylladb/care-pet#55]
The docs preview doesn't work on MacOS.
OS: Big Sur 11.5.2

```
docs (master) $ make preview
./_utils/setup.sh
/usr/bin/python3
/Users/raoufchebri/.poetry/bin/poetry
Traceback (most recent call last):
  File "/Users/raoufchebri/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/Users/raoufchebri/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/raoufchebri/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/Users/raoufchebri/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/Users/raoufchebri/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/Users/raoufchebri/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/Users/raoufchebri/.poetry/lib/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/Users/raoufchebri/.poetry/lib/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/Users/raoufchebri/.poetry/lib/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 5, in <module>
    from backports.entry_points_selectable import entry_points
ImportError: No module named entry_points_selectable
Traceback (most recent call last):
  File "/Users/raoufchebri/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/Users/raoufchebri/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/raoufchebri/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/Users/raoufchebri/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/Users/raoufchebri/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/Users/raoufchebri/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/Users/raoufchebri/.poetry/lib/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/Users/raoufchebri/.poetry/lib/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/Users/raoufchebri/.poetry/lib/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 5, in <module>
    from backports.entry_points_selectable import entry_points
ImportError: No module named entry_points_selectable
make: *** [setup] Error 1
```

**Comment by tzach** [comment]
@dgarcia360 can you please take a look?

**Comment by dgarcia360** [comment]
Hi @raoufchebri,

Looks like you are using python 2.7, but the documentation toolchain is compatible with [Python 3.7 onwards](https://sphinx-theme.scylladb.com/stable/getting-started/installation.html#prerequisites).

> File "/Users/raoufchebri/.poetry/lib/poetry/_vendor/**py2.7**/virtualenv/__init__.py", line 3, in <module>

Could you please try to install Python 3.7+ and run the command again?
